### ISSUE TITLE
Question on v2 branch

### ISSUE THREAD

**Issue by Tank-Missile** [numixproject/numix-folders#186]
I noticed there was a v2 branch. Is that branch abandoned, or should I focus on it for adding features, etc?

**Comment by palob** [comment]
v2 is the way to go. @bilelmoussaoui Did you work on it since your last commit?

**Comment by bilelmoussaoui** [comment]
Oh, I completely forgot that I started a rewrite a long time ago. Feel free to you use that, but it's not working at all. If you need any guidance or help getting something working, please ping me.

**Comment by Tank-Missile** [comment]
If that's the case, perhaps I should just start from scratch? I was hoping to make a better UI in Qt. Obviously, it would be a frontend to the existing cli. I may even rewrite that since I've found issues with it, such as it not accepting color input, etc.

**Comment by bilelmoussaoui** [comment]
I haven't done any Qt in a while, not sure I would be able to review your work later. Let's see what @palob & @Foggalong think about this

**Comment by palob** [comment]
The current implementation uses PyGObject. @Tank-Missile But if you want to contribute and fix the issues you are free to do whatever floats your boat.

**Comment by Foggalong** [comment]
I'd sooner not have it in Qt for the plain and simple reason that the vast majority of Numix users are using a GTK based distribution. Having this app be Qt would mean that a load of additional dependencies the user likely doesn't have would need bringing in.

I don't actually use the GUI version of this at all but I'm not opposed to someone else coming in and rewriting the UI from scratch if it's going to be an improvement / fix to what we currently have. I'm aware it's probably some time since it had some love.
