### ISSUE TITLE
(Question) Icons in 16x16/places only complete for default colour, all colours in Numix base

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#26]
This one is a question: Am I correct in assuming that the complete set of folder icons in `16x16/places` is only present for the default colour (and only the icons changing with the folder style in all colours), because all the colours in this size are present in Numix base?

This makes sense because the majority of the icons in `16x16/places` has the same design and thus does not need to be present in the non-default colours in all 6 Folder Styles; it is more efficient to simply have them in Numix base right away.

And could this potentially cause a problem in case that s.o./s.th. is searching for these icons in "Numix-Folders" and not in Numix base (quite unlikely, but I was just wondering)?

Screenshot of Style No. 6, to illustrate that only the default colour folder icon set is complete in `16x16/places`:

![6_16](https://cloud.githubusercontent.com/assets/7164227/6512286/111cb5c8-c373-11e4-9be1-131a45ab30a5.png)

**Comment by Foggalong** [comment]
Yeah, I'll explain this. The way the switcher works is by copying all the icons from the selected style folder and [pasting with overwrite into the base theme](https://github.com/numixproject/numix-folders/blob/master/script.sh#L86). As an aside, this means a few things:

1. All the styles need to contain the same icons. If they don't then it can cause breakage when switching between multiple styles, leaving the one not covered in a particular style looking like the style used before. 

2. The styles **don't** have to contain any symlinks. All that needs to be covered is the root icon, and all the symlinks will do their thing and update automatically.

3. If you want 2 icons in a particular style to be the same when they wouldn't need to be, you **do** need to include the symlink. See `fileopen.svg` and `folder-open.svg` in style 4 as an example.

Anyway, because the 16px folders are just symbols the coloured versions are the same regarless of what style they're for. That means the icons in base never need to be overwritten. The only exception is the default colour because that switches based on style, hence it's inclusion.
