### ISSUE TITLE
Clean icon cache after executing the script

### ISSUE THREAD

**Issue by neitsab** [numixproject/numix-folders#40]
Hi,

I believe it would be helpful to either add a pointer at the end of `README.md` or directly include this step in the script on how to clean the icon cache after executing the script. It took me a while to figure that despite doing <kbd>Alt</kbd>-<kbd>F2</kbd> `gnome-shell --replace` the folder icons would remain those of the old (default) style and colour.

I found in #30 the way to do this: `sudo gtk-update-icon-cache -f /usr/share/icons/Numix` (if that's where your Numix icon theme is installed), which worked as expected.

Thanks for your great work!

**Comment by dirtydancing** [comment]
Hi, does the terminal command `nautilus -q` and then re-opening Nautilus work for you?

This might be and easier way to go about this. I usually do that now and get along fine with it. As I use folder style 5, I have to do this every time a Numix base PPA update comes in, because that restores the default folder style 6. Or am I missing s.th. here?

I am not sure if pointing the users to `sudo gtk-update-icon-cache -f /usr/share/icons/Numix` in the readme is a good idea. This might be somewhat intimidating, it is a `sudo` command after all, and as you already mentioned it depends on where the Numix icon theme is installed.

**Comment by Foggalong** [comment]
I was originally thinking we wouldn't be able to do this because it requires `sudo`, but it seems that `gtk-update-icon-cache` only uses that for global installations and it can still do it without for ones installed locally. I'll see where I can work this in :)
