### ISSUE TITLE
Problem with default colour switcher script

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#51]
I am running into difficulties with the default colour switcher, cf. https://github.com/numixproject/numix-folders/pull/50. When doing some testing, also in combination with Folder Color (only using Folder Color for individual folders, not Folder Color's global feature), I somehow ended up like this:

![folder-colours_1](https://cloud.githubusercontent.com/assets/7164227/7347218/87f0b4aa-ece6-11e4-974f-c54365f9d054.png)

I am not sure how to reproduce that, but this happened after I deliberately entered some wrong values for folder style and folder colour when running the script, so this might have to do with that. What I also noticed is that when then using Folder Color for individual folders, this worked for some colours, but not for others (marked in the screenshot below):

![folder-colours_2](https://cloud.githubusercontent.com/assets/7164227/7347236/c1269640-ece6-11e4-8ae9-5443796b86f8.png)

Is this just me, or is there a problem with the default colour switching script, or is this a problem when the script (for the default colour) and Folder Color (for individual folders) are used in combination?

@costales pinging you on this one, in case there might be a problem from Folder Color's side :)

**Comment by costales** [comment]
Hi! :) How are you?

I'm thinking is not a Folder Color issue, because you say:
"only using Folder Color for individual folders, not Folder Color's global
feature"
With individual folders, this should not apply,

Could you try these commands? They will tell us a few things about the
current wrong folder :)
gvfs-info -a metadata::emblems ~/Projekte
gvfs-info -a metadata::custom-icon-name ~/Projekte
gvfs-info -a metadata::custom-icon ~/Projekte


But Folder Color should find the Numix icons, not the Humanity icons as in
your screenshot, could you try this command too?
find /usr/share/icons/<Numix> -name "folder_color_blue.svg"
Please, change <Numix> for your Numix icon, I'm not sure which are :)
Numix-Circle-Light?

Best regards! |o/

**Comment by Foggalong** [comment]
Yeah, as was discussed in the last pull request the colour changing doesn't work if you enter a wrong value. I've got the fix for it it just requires some restructuring.

**Comment by Foggalong** [comment]
@costales I didn't realise you'd shipped the global colour changing - that really shouldn't come under Folder Color unless you have plans to add support for icons like `folder-move` because people are going to end up with inconsistent interfaces.

It'd be fine if you were only doing it for one theme (I.e. humanity) because you could always be sure you were covering everything, but because it's supposed to go with any theme you'll never be able to be sure if you're getting everything.

I'd honestly advise you to leave global colour switching to the individual theme providors because they're the only ones who hard gonna be able to make sure it's done correctly for their theme. That's how it's done with Ozon, Numix, Nitrux, Faenza, ACYL, and probably others too.

**Comment by costales** [comment]
Hi @Foggalong :) It's not a problem. It is working fine and it's just focused into standard installations, as Ubuntu or Ubuntu MATE.
For Numix icons is perfect your implementation :)

**Comment by dirtydancing** [comment]
Good to hear that this is a known issue in the Numix script! Re-installing Numix base "fixed" it. I thought this was ready to go, and I wanted to give you a heads-up before the official announcement is made :)

**Comment by dirtydancing** [comment]
@costales Is there a way to only display the global colour change option in Folder Color when Humanity is used? I am asking because the users might get confused when they are offered a "global"/"default" colour change in both Folder Color as well as in the Numix-Folders switcher script. And as far as I can tell, for the global/default folder colour switch, the Numix script is the way to go for Numix icon theme.

**Comment by Foggalong** [comment]
Yeah, a humanity only switch would be ace.

**Comment by costales** [comment]
> a way to only display the global colour change option in Folder Color 
when Humanity is used?

Not yet. I'll think on it :)

**Comment by costales** [comment]
@Foggalong Could you create a dummy file anywhere? Something as "folder_color_hide"?
If Folder Color finds that file, Folder Color hides the Global Color option. That will allow to the artwork designers to allow or not a Folder Color switcher :)

**Comment by Foggalong** [comment]
No offense, but that's a very poor way to do it. Every theme I know of that offers different coloured folders does the changing by their own methods so the catch would have to go in all of them rather than just making yours humanity only :/

**Comment by dirtydancing** [comment]
Please correct me if I am wrong: As I understand it, Folder Color works for different icon themes, but only for those icon themes that include special `folder_color_*` icons/symlinks. Would this not mean that only those icon themes that intend Folder Color to work for them at all and that are using these special named folders would have to include that catch, if they choose to include it? And currently that would only be the Numix and Vibrancy Colors icon themes? Just asking.

As for the naming of such dummy file: I would like to suggest to include "global" in that name, so as to make clear from the outset what that file is for, e.g. `folder_color_hide_global`. Just a suggestion.

**Comment by dirtydancing** [comment]
Or alternatively the other way around: `folder_color_unhide_global` or the like, and only those icon themes that have that file will display the Folder Color global switch option :)

**Comment by Foggalong** [comment]
Yeah, currently it's only Numix that supports this (possibly gonna be able to do Ozon too) so it's odd that we're even having this conversation.

As for the tag, it just shouldn't be there at all. As said, humanity is the only theme you can garuntee full support for so it should be the only one with the option. Or you could scrap the feature completely and leave it down to the themes as is currently the case (my preference, but either is good).

**Comment by dirtydancing** [comment]
Well, I figure we are having this conversation because the global feature in Folder Color has been around for a while already :) I have pointed to some limitations of that feature e.g. in this thread https://github.com/numixproject/numix-icon-theme/issues/304, and since then there have been improvements in Folder Color e.g. for the small sizes. But still, from what I have seen so far, the Numix script is the better way to deal with the global/default switch, and thus the Numix script should be the only way to deal with this.

Agreed that currently, the global feature for Folder Color only applies to Humanity. As I understood it, @costales wanted to offer that feature to the creators of other icon themes that would be interested in it. That is why I suggested the alternative "on"-switch. That way, other icon themes in the future could "opt-in" to the global feature of Folder Color, while the standard would be that it is not displayed. So this would maybe even encourage more already existing themes to include support for Folder Color, because they would not have to worry about conflicting global/default switches :)

**Comment by Foggalong** [comment]
The Folder Color feature was only implemented after I'd discussed the possibility of the numix feature *and* pointed out that it couldn't be imolemented generally clearly, which is why I'm confused.

As for why not opt in - as I said above all the themes I know of that offer the feature already do so by their own means. Though even if it were to be made opt-in it'd need improving to include the full range of folder icons a theme can have (which again isn't necessarily consistent across different themes).

**Comment by dirtydancing** [comment]
Understood, thanks for clarifying. I am sure this will get sorted for the continuing benefit of the users :)

**Comment by Foggalong** [comment]
@dirtydancing Not at all! It's easy to see why it would be thought otherwise because the conversation was hand over email rather than on a public tracker.

@costales as said, I hope we can get this sorted. Now I'm focusing on Folders again it'd be nice to be able to release without this hanging over things.

**Comment by costales** [comment]
Hi there!

I'll not remove that feature :) because (I think) is a great feature for
other themes or Humanity instead.

But it will be hidden by default and the theme can force to show it just
creating this icon: folder_color_globalcolor.svg in any resolution.
Related bug: https://bugs.launchpad.net/folder-color/+bug/1449172
With this, Folder Color will not have that option with Numix.

Best regards!

**Comment by Foggalong** [comment]
I guess having it as a opt-in feature is a fair compromise :) after I've cleaned the last few Folders bugs up I'll make the announcement then

**Comment by dirtydancing** [comment]
Great! And confirmed that with Folder Color's latest version 0.0.76 of today via PPA, Folder Color's global color option does not show anymore for Numix icon theme. I just checked on Ubuntu 14.10.
