### ISSUE TITLE
${colour}-folder-open.svg is missing in all sizes in style 3

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-folders#61]
I think the title says it all. I think they used to be a symlink to ${colour}-fileopen.svg, am I right? They got  probably llost at some point

**Comment by Foggalong** [comment]
We don't have symlinks in Numix Folders since it only needs to replace the source icon for the change to take affect.

**Comment by wa4557** [comment]
Ah ok :)

**Comment by Foggalong** [comment]
Oh wait, was this the one symlink thay we did have?

**Comment by wa4557** [comment]
Yeah you did

**Comment by Foggalong** [comment]
One of the syles did have on symlink for one specific icon and I'm thinking this was it.

**Comment by Foggalong** [comment]
Oh er, what else is broken?

**Comment by wa4557** [comment]
Just the symlinks pointing to {color}-fileopen.svg in style 3

**Comment by Foggalong** [comment]
Ah, goodo.

**Comment by wa4557** [comment]
Should I do that?

**Comment by Foggalong** [comment]
If you're free to yeah, othereise I can bash it out tomorrow :)

**Comment by Foggalong** [comment]
We did originally say no to custom colours when @coastels asked. The reasoning given then was that there would never be an upper limit on the number of colours we'd include in a folder icon.

However, because this is an in house solution we cam always just up the number of variables if it does ever increase.

If the script does work with icons with different numbers of course (i.e. style 2 which only uses 2) then I'll see about possibly including this :)

**Comment by wa4557** [comment]
Yeah, I think this approach is quite flexible. In principle you could adjust as many colours as you want with a little bit of tweaking in the script, and of course if the style only uses 2 colours only 2 colours are replaced
