### ISSUE TITLE
File Manager app icon

### ISSUE THREAD

**Issue by Sadi58** [numixproject/numix-folders#90]
How about including also File Manager app icon in the color replacement process by (i) changing the color of the folder there, and perhaps also (ii) changing the background color as well?
For example, I use a Blue folder with a Silver background.

**Comment by Foggalong** [comment]
I considered this when making the folders for app icons, but it turned out to be way too complicated to implement design wise. While at then same time making sure that the background colour and folder colour match up nicely you then have to make sure you keep any branding colours (like green with Nemo) in there too. It ends up being pretty much impossible to juggle all the criteria and the design quality suffers massively because of it.

**Comment by Sadi58** [comment]
Hmmm, makes sense... Then another alternative could be designing the File Manager app icon in a way that doesn't simply copy the base folder icon (which looks a bit "inconsistent" when another folder color is used)

**Comment by Foggalong** [comment]
Doesn't really work because we have different styles already available as global options, so the inconsistency within a style would just be confusing.
